# Auto-generated: every skill in skill_categories_data.SKILL_TYPE_IDS (the
# same 510-skill, personal-playstyle-relevant universe used for tips),
# grouped by its REAL EVE skill group — resolved once via each skill's
# live group_id (/universe/types/{id}/) and that group's name
# (/universe/groups/{id}/), not the 5 curated playstyle categories used
# elsewhere. Do not hand-edit; regenerate from ESI if the game adds skills.
#
# Of the 25 real groups under the Skills category, 4 don't appear here at
# all: "Fake Skills" and "Sequencing" (no player-trainable skills in the
# tracked universe), and the corp/sovereignty-leadership skills already
# excluded from SKILL_TYPE_IDS happen to leave no residue in these two
# groups either. "Corporation Management" and "Structure Management" DO
# appear, just small — they hold personally-relevant skills (Factory/
# Refinery/Station Management; Anchoring) distinct from the excluded
# corp-leadership skills that share the same broader ESI category.

SKILL_GROUPS = {
    'Armor': ['Advanced Armor Layering', 'Armor Layering', 'Capital Remote Armor Repair Systems', 'Capital Remote Hull Repair Systems', 'Capital Repair Systems', 'EM Armor Compensation', 'Explosive Armor Compensation', 'Hull Upgrades', 'Kinetic Armor Compensation', 'Mechanics', 'Remote Armor Repair Systems', 'Remote Hull Repair Systems', 'Repair Systems', 'Thermal Armor Compensation'],
    'Corporation Management': ['Factory Management', 'Refinery Management', 'Station Management'],
    'Drones': ['Advanced Drone Avionics', 'Amarr Drone Specialization', 'Amarr Fighter Specialization', 'Caldari Drone Specialization', 'Caldari Fighter Specialization', 'Drone Avionics', 'Drone Durability', 'Drone Interfacing', 'Drone Navigation', 'Drone Sharpshooting', 'Drones', 'Fighter Hangar Management', 'Fighters', 'Gallente Drone Specialization', 'Gallente Fighter Specialization', 'Heavy Drone Operation', 'Heavy Fighters', 'Ice Harvesting Drone Operation', 'Ice Harvesting Drone Specialization', 'Light Drone Operation', 'Light Fighters', 'Medium Drone Operation', 'Mining Drone Operation', 'Mining Drone Specialization', 'Minmatar Drone Specialization', 'Minmatar Fighter Specialization', 'Mutated Drone Specialization', 'Propulsion Jamming Drone Interfacing', 'Repair Drone Operation', 'Salvage Drone Operation', 'Salvage Drone Specialization', 'Sentry Drone Interfacing', 'Support Fighters'],
    'Engineering': ['Advanced Energy Grid Upgrades', 'Advanced Weapon Upgrades', 'CPU Management', 'Capacitor Emission Systems', 'Capacitor Management', 'Capacitor Systems Operation', 'Capital Capacitor Emission Systems', 'Electronics Upgrades', 'Energy Grid Upgrades', 'Energy Pulse Weapons', 'Nanite Interfacing', 'Nanite Operation', 'Power Grid Management', 'Resistance Phasing', 'Thermodynamics', 'Weapon Upgrades'],
    'Fleet Support': ['Armored Command', 'Armored Command Specialist', 'Command Burst Specialist', 'Expedition Command', 'Expedition Command Specialist', 'Fleet Command', 'Fleet Compression Logistics', 'Fleet Coordination', 'Fleet Formations', 'Information Command', 'Information Command Specialist', 'Leadership', 'Mining Director', 'Mining Foreman', 'Shield Command', 'Shield Command Specialist', 'Skirmish Command', 'Skirmish Command Specialist', 'Spatial Phenomena Generation', 'Wing Command'],
    'Gunnery': ['Advanced Doomsday Operation', 'Capital Artillery Specialization', 'Capital Autocannon Specialization', 'Capital Beam Laser Specialization', 'Capital Blaster Specialization', 'Capital Disintegrator Specialization', 'Capital Energy Turret', 'Capital Hybrid Turret', 'Capital Precursor Weapon', 'Capital Projectile Turret', 'Capital Pulse Laser Specialization', 'Capital Railgun Specialization', 'Controlled Bursts', 'Disruptive Lance Operation', 'Doomsday Operation', 'Doomsday Rapid Firing', 'Gunnery', 'Large Artillery Specialization', 'Large Autocannon Specialization', 'Large Beam Laser Specialization', 'Large Blaster Specialization', 'Large Disintegrator Specialization', 'Large Energy Turret', 'Large Hybrid Turret', 'Large Precursor Weapon', 'Large Projectile Turret', 'Large Pulse Laser Specialization', 'Large Railgun Specialization', 'Large Vorton Projector', 'Large Vorton Specialization', 'Medium Artillery Specialization', 'Medium Autocannon Specialization', 'Medium Beam Laser Specialization', 'Medium Blaster Specialization', 'Medium Disintegrator Specialization', 'Medium Energy Turret', 'Medium Hybrid Turret', 'Medium Precursor Weapon', 'Medium Projectile Turret', 'Medium Pulse Laser Specialization', 'Medium Railgun Specialization', 'Medium Vorton Projector', 'Medium Vorton Specialization', 'Motion Prediction', 'Rapid Firing', 'Sharpshooter', 'Small Artillery Specialization', 'Small Autocannon Specialization', 'Small Beam Laser Specialization', 'Small Blaster Specialization', 'Small Disintegrator Specialization', 'Small Energy Turret', 'Small Hybrid Turret', 'Small Precursor Weapon', 'Small Projectile Turret', 'Small Pulse Laser Specialization', 'Small Railgun Specialization', 'Small Vorton Projector', 'Small Vorton Specialization', 'Surgical Strike', 'Tactical Strike', 'Tactical Weapon Reconfiguration', 'Trajectory Analysis', 'Vorton Arc Extension', 'Vorton Arc Guidance', 'Vorton Power Amplification', 'Vorton Projector Operation'],
    'Missiles': ['Auto-Targeting Missiles', 'Bomb Deployment', 'Breacher Pod Clone Efficacity', 'Breacher Pod Clone Longevity', 'Breacher Pod Launcher Operation', 'Breacher Pod Projection', 'Breacher Pod Rapid Firing', 'Cruise Missile Specialization', 'Cruise Missiles', 'Defender Missiles', 'Guided Missile Precision', 'Heavy Assault Missile Specialization', 'Heavy Assault Missiles', 'Heavy Missile Specialization', 'Heavy Missiles', 'Light Missile Specialization', 'Light Missiles', 'Missile Bombardment', 'Missile Launcher Operation', 'Missile Projection', 'Rapid Launch', 'Rocket Specialization', 'Rockets', 'Target Navigation Prediction', 'Torpedo Specialization', 'Torpedoes', 'Warhead Upgrades', 'XL Cruise Missile Specialization', 'XL Cruise Missiles', 'XL Torpedo Specialization', 'XL Torpedoes'],
    'Navigation': ['Acceleration Control', 'Afterburner', 'Capital Jump Portal Generation', 'Capital Micro Jump Drive Operation', 'Cynosural Field Theory', 'Evasive Maneuvering', 'Fuel Conservation', 'High Speed Maneuvering', 'Jump Drive Calibration', 'Jump Drive Operation', 'Jump Fuel Conservation', 'Jump Portal Generation', 'Micro Jump Drive Operation', 'Navigation', 'Warp Drive Operation'],
    'Neural Enhancement': ['Advanced Infomorph Psychology', 'Biology', 'Cloning Facility Operation', 'Cybernetics', 'Elite Infomorph Psychology', 'Infomorph Psychology', 'Infomorph Synchronizing', 'Neurotoxin Control', 'Neurotoxin Recovery'],
    'Production': ['Advanced Capital Ship Construction', 'Advanced Industrial Ship Construction', 'Advanced Industry', 'Advanced Large Ship Construction', 'Advanced Mass Production', 'Advanced Medium Ship Construction', 'Advanced Small Ship Construction', 'Amarr Tech', 'Caldari Tech', 'Capital Ship Construction', 'Drug Manufacturing', 'Gallente Tech', 'Industry', 'Mass Production', 'Minmatar Tech', 'Mobile Factory Operation', 'Outpost Construction', 'Supply Chain Management'],
    'Resource Processing': ['Abyssal Ore Processing', 'Advanced Mass Reactions', 'Arkonor Processing', 'Astrogeology', 'Bezdnacine Processing', 'Bistot Processing', 'Capital Industrial Reconfiguration', 'Capital Shipboard Compression Technology', 'Coherent Ore Processing', 'Common Moon Ore Processing', 'Complex Ore Processing', 'Crokite Processing', 'Dark Ochre Processing', 'Deep Core Mining', 'Erratic Ore Processing', 'Exceptional Moon Ore Processing', 'Gas Cloud Harvesting', 'Gas Decompression Efficiency', 'Gneiss Processing', 'Hedbergite Processing', 'Hemorphite Processing', 'Ice Harvesting', 'Ice Processing', 'Industrial Reconfiguration', 'Jaspet Processing', 'Kernite Processing', 'Mass Reactions', 'Mercoxit Ore Processing', 'Mining', 'Mining Exploitation', 'Mining Precision', 'Mining Upgrades', 'Mobile Refinery Operation', 'Omber Processing', 'Ore Compression', 'Plagioclase Processing', 'Pyroxeres Processing', 'Rakovene Processing', 'Rare Moon Ore Processing', 'Reactions', 'Remote Reactions', 'Reprocessing', 'Reprocessing Efficiency', 'Salvaging', 'Scordite Processing', 'Scrapmetal Processing', 'Shipboard Compression Technology', 'Simple Ore Processing', 'Spodumain Processing', 'Talassonite Processing', 'Ubiquitous Moon Ore Processing', 'Uncommon Moon Ore Processing', 'Unrefined Minerals Processing', 'Variegated Ore Processing', 'Veldspar Processing'],
    'Rigging': ['Armor Rigging', 'Astronautics Rigging', 'Drones Rigging', 'Electronic Superiority Rigging', 'Energy Weapon Rigging', 'Hybrid Weapon Rigging', 'Jury Rigging', 'Launcher Rigging', 'Projectile Weapon Rigging', 'Shield Rigging'],
    'Scanning': ['Archaeology', 'Astrometric Acquisition', 'Astrometric Pinpointing', 'Astrometric Rangefinding', 'Astrometrics', 'Hacking', 'Survey'],
    'Science': ['Advanced Laboratory Operation', 'Amarr Encryption Methods', 'Amarr Starship Engineering', 'Astronautic Engineering', 'Caldari Encryption Methods', 'Caldari Starship Engineering', 'Core Subsystem Technology', 'Defensive Subsystem Technology', 'Electromagnetic Physics', 'Electronic Engineering', 'Electronic Subsystem Technology', 'Gallente Encryption Methods', 'Gallente Starship Engineering', 'Graviton Physics', 'High Energy Physics', 'Hydromagnetic Physics', 'Hypernet Science', 'Laboratory Operation', 'Laser Physics', 'Mechanical Engineering', 'Metallurgy', 'Minmatar Encryption Methods', 'Minmatar Starship Engineering', 'Molecular Engineering', 'Mutagenic Stabilization', 'Nanite Engineering', 'Nuclear Physics', 'Offensive Subsystem Technology', 'Plasma Physics', 'Propulsion Subsystem Technology', 'Quantum Physics', 'Research', 'Research Project Management', 'Rocket Science', 'Science', 'Scientific Networking', 'Sleeper Encryption Methods', 'Sleeper Technology', 'Takmahl Technology', 'Talocan Technology', 'Triglavian Encryption Methods', 'Triglavian Quantum Engineering', 'Upwell Encryption Methods', 'Upwell Starship Engineering', 'Yan Jung Technology'],
    'Shields': ['Advanced Shield Upgrades', 'Capital Shield Emission Systems', 'Capital Shield Operation', 'EM Shield Compensation', 'Explosive Shield Compensation', 'Invulnerability Core Operation', 'Kinetic Shield Compensation', 'Shield Compensation', 'Shield Emission Systems', 'Shield Management', 'Shield Operation', 'Shield Upgrades', 'Tactical Shield Manipulation', 'Thermal Shield Compensation'],
    'Social': ['Connections', 'Criminal Connections', 'DED Connections', 'Diplomacy', 'Distribution Connections', 'Fast Talk', 'Freelancing', 'Mining Connections', 'Negotiation', 'Security Connections', 'Social'],
    'Spaceship Command': ['Advanced Spaceship Command', 'Amarr Battlecruiser', 'Amarr Battleship', 'Amarr Carrier', 'Amarr Cruiser', 'Amarr Destroyer', 'Amarr Dreadnought', 'Amarr Force Auxiliary', 'Amarr Freighter', 'Amarr Frigate', 'Amarr Hauler', 'Amarr Strategic Cruiser', 'Amarr Tactical Destroyer', 'Amarr Titan', 'Assault Frigates', 'Battlecruisers', 'Black Ops', 'Caldari Battlecruiser', 'Caldari Battleship', 'Caldari Carrier', 'Caldari Cruiser', 'Caldari Destroyer', 'Caldari Dreadnought', 'Caldari Force Auxiliary', 'Caldari Freighter', 'Caldari Frigate', 'Caldari Hauler', 'Caldari Strategic Cruiser', 'Caldari Tactical Destroyer', 'Caldari Titan', 'Capital Industrial Ships', 'Capital Ships', 'Command Carriers', 'Command Destroyers', 'Command Ships', 'Covert Ops', 'Destroyers', 'Electronic Attack Ships', 'Exhumers', 'Expedition Command Ships', 'Expedition Frigates', 'Gallente Battlecruiser', 'Gallente Battleship', 'Gallente Carrier', 'Gallente Cruiser', 'Gallente Destroyer', 'Gallente Dreadnought', 'Gallente Force Auxiliary', 'Gallente Freighter', 'Gallente Frigate', 'Gallente Hauler', 'Gallente Strategic Cruiser', 'Gallente Tactical Destroyer', 'Gallente Titan', 'Heavy Assault Cruisers', 'Heavy Interdiction Cruisers', 'Industrial Command Ships', 'Interceptors', 'Interdictors', 'Jump Freighters', 'Lancer Dreadnoughts', 'Logistics Cruisers', 'Logistics Frigates', 'Marauders', 'Mining Barge', 'Mining Destroyer', 'Mining Frigate', 'Minmatar Battlecruiser', 'Minmatar Battleship', 'Minmatar Carrier', 'Minmatar Cruiser', 'Minmatar Destroyer', 'Minmatar Dreadnought', 'Minmatar Force Auxiliary', 'Minmatar Freighter', 'Minmatar Frigate', 'Minmatar Hauler', 'Minmatar Strategic Cruiser', 'Minmatar Tactical Destroyer', 'Minmatar Titan', 'ORE Freighter', 'ORE Hauler', 'Recon Ships', 'Spaceship Command', 'Transport Ships', 'Upwell Freighter', 'Upwell Hauler'],
    'Structure Management': ['Anchoring'],
    'Subsystems': ['Amarr Core Systems', 'Amarr Defensive Systems', 'Amarr Electronic Systems', 'Amarr Offensive Systems', 'Amarr Propulsion Systems', 'Caldari Core Systems', 'Caldari Defensive Systems', 'Caldari Electronic Systems', 'Caldari Offensive Systems', 'Caldari Propulsion Systems', 'Gallente Core Systems', 'Gallente Defensive Systems', 'Gallente Electronic Systems', 'Gallente Offensive Systems', 'Gallente Propulsion Systems', 'Minmatar Core Systems', 'Minmatar Defensive Systems', 'Minmatar Electronic Systems', 'Minmatar Offensive Systems', 'Minmatar Propulsion Systems'],
    'Targeting': ['Advanced Target Management', 'Gravimetric Sensor Compensation', 'Ladar Sensor Compensation', 'Long Range Targeting', 'Magnetometric Sensor Compensation', 'Radar Sensor Compensation', 'Signature Analysis', 'Target Management'],
    'Trade': ['Accounting', 'Advanced Broker Relations', 'Advanced Contracting', 'Black Market Trading', 'Broker Relations', 'Consumable Freight', 'Contracting', 'Corporation Contracting', 'Customs Code Expertise', 'Daytrading', 'Drone Freight', 'General Freight', 'Hazardous Material Freight', 'Marketing', 'Mineral Freight', 'Munitions Freight', 'Procurement', 'Raw Material Freight', 'Retail', 'Smuggling', 'Starship Freight', 'Tax Evasion', 'Trade', 'Tycoon', 'Visibility', 'Wholesale'],
}
