# Auto-generated from live ESI skill-group data (all 25 real skill groups
# under the Skill category, captured name+type_id directly from
# /universe/groups/ + /universe/names/ — not the fuzzy /universe/ids/
# search endpoint, which proved unreliable for exact skill names).
# Do not hand-edit SKILL_TYPE_IDS/FULL_SKILL_NAMES; regenerate via
# gen_skill_data.py instead if the game adds/removes skills.
# CORE_TARGETS is hand-curated (see project_personalization_roadmap memory
# for the history) and NOT auto-regenerated — gen_skill_data.py only ever
# removes entries here that are no longer real skills.
#
# 483 of 511 real, currently-published,
# player-trainable skills are covered. See gen_skill_data.py's docstring for
# what's excluded and why, and how to review newly-added skills before
# folding them in.
#
# CORE_TARGETS holds the hand-picked "this actually matters" skills per
# category with specific recommended levels — always shown regardless of
# trained level. Every other skill in FULL_SKILL_NAMES defaults to a target
# of 5 (max).

CORE_TARGETS = {'Mining': {'Mining': 5, 'Astrogeology': 5, 'Mining Upgrades': 5, 'Mining Frigate': 5, 'Mining Barge': 5, 'Exhumers': 5, 'Ice Harvesting': 4, 'Gas Cloud Harvesting': 4, 'Deep Core Mining': 4, 'Simple Ore Processing': 4, 'Coherent Ore Processing': 4, 'Complex Ore Processing': 4, 'Variegated Ore Processing': 4, 'Erratic Ore Processing': 4, 'Abyssal Ore Processing': 4, 'Ubiquitous Moon Ore Processing': 4, 'Common Moon Ore Processing': 4, 'Uncommon Moon Ore Processing': 4, 'Rare Moon Ore Processing': 4, 'Exceptional Moon Ore Processing': 4, 'Spaceship Command': 5, 'CPU Management': 5, 'Power Grid Management': 5, 'Capacitor Management': 4, 'Capacitor Systems Operation': 4, 'Mechanics': 5, 'Hull Upgrades': 5, 'Shield Management': 4, 'Shield Operation': 4, 'Long Range Targeting': 4, 'Signature Analysis': 4, 'Navigation': 5, 'Evasive Maneuvering': 5, 'Warp Drive Operation': 5, 'Mining Drone Operation': 5, 'Mining Drone Specialization': 5, 'Ice Harvesting Drone Operation': 4, 'Ice Harvesting Drone Specialization': 4}, 'Industry': {'Industry': 5, 'Advanced Industry': 5, 'Mass Production': 5, 'Advanced Mass Production': 4, 'Laboratory Operation': 5, 'Advanced Laboratory Operation': 4, 'Metallurgy': 5, 'Research': 5, 'Science': 5, 'Reprocessing': 4, 'Reprocessing Efficiency': 4, 'Supply Chain Management': 3, 'Accounting': 5, 'Broker Relations': 5, 'Advanced Broker Relations': 4}, 'Mission Running': {'Spaceship Command': 5, 'Drones': 5, 'Shield Management': 5, 'Shield Operation': 4, 'Hull Upgrades': 5, 'Mechanics': 5, 'Repair Systems': 4, 'Tactical Shield Manipulation': 3, 'Target Management': 4, 'Long Range Targeting': 4, 'Signature Analysis': 4, 'Social': 4, 'Connections': 4, 'Negotiation': 4, 'Diplomacy': 4}, 'PVP': {'Spaceship Command': 5, 'Gunnery': 5, 'Missile Launcher Operation': 5, 'Drones': 5, 'Evasive Maneuvering': 5, 'Afterburner': 5, 'High Speed Maneuvering': 4, 'Propulsion Jamming': 4, 'Electronic Warfare': 4, 'Weapon Disruption': 4, 'Sensor Linking': 4, 'Signature Analysis': 4, 'Target Management': 4, 'Shield Management': 4, 'Hull Upgrades': 4, 'Criminal Connections': 4, 'Fast Talk': 4, 'CPU Management': 5, 'Power Grid Management': 5, 'Capacitor Management': 4, 'Capacitor Systems Operation': 4, 'Mechanics': 5, 'Shield Operation': 4, 'Long Range Targeting': 4, 'Navigation': 5, 'Warp Drive Operation': 5, 'Amarr Frigate': 5, 'Caldari Frigate': 5, 'Minmatar Frigate': 5, 'Gallente Frigate': 5, 'Minmatar Destroyer': 5, 'Sharpshooter': 4, 'Trajectory Analysis': 4, 'Motion Prediction': 4, 'Rapid Firing': 4, 'Surgical Strike': 4, 'Controlled Bursts': 4, 'Rapid Launch': 4, 'Missile Bombardment': 4, 'Warhead Upgrades': 4, 'Guided Missile Precision': 4, 'Light Drone Operation': 4, 'Medium Drone Operation': 4, 'Heavy Drone Operation': 4, 'Sentry Drone Interfacing': 4, 'Drone Interfacing': 4, 'Amarr Drone Specialization': 4, 'Caldari Drone Specialization': 4, 'Gallente Drone Specialization': 4, 'Minmatar Drone Specialization': 4}, 'Quality of Life': {'CPU Management': 5, 'Power Grid Management': 5, 'Weapon Upgrades': 5, 'Advanced Weapon Upgrades': 4, 'Navigation': 5, 'Warp Drive Operation': 5, 'Fuel Conservation': 4, 'Acceleration Control': 4, 'Cybernetics': 4, 'Infomorph Psychology': 4, 'Broker Relations': 4, 'Trade': 4, 'Accounting': 4, 'Jury Rigging': 4, 'Capacitor Management': 4, 'Capacitor Systems Operation': 4}, 'Exploration': {'Astrometrics': 5, 'Astrometric Rangefinding': 4, 'Astrometric Pinpointing': 4, 'Hacking': 4, 'Archaeology': 4, 'Astrometric Acquisition': 3, 'Survey': 3}}

# name -> type_id, resolved directly (not via fuzzy search)
SKILL_TYPE_IDS = {
    'Abyssal Ore Processing': 60381,
    'Acceleration Control': 3452,
    'Accounting': 16622,
    'Advanced Armor Layering': 89689,
    'Advanced Broker Relations': 16597,
    'Advanced Capital Ship Construction': 77725,
    'Advanced Contracting': 73912,
    'Advanced Doomsday Operation': 88377,
    'Advanced Drone Avionics': 23566,
    'Advanced Industrial Ship Construction': 3396,
    'Advanced Industry': 3388,
    'Advanced Infomorph Psychology': 33407,
    'Advanced Laboratory Operation': 24624,
    'Advanced Large Ship Construction': 3398,
    'Advanced Mass Production': 24625,
    'Advanced Mass Reactions': 45749,
    'Advanced Medium Ship Construction': 3397,
    'Advanced Planetology': 2403,
    'Advanced Small Ship Construction': 3395,
    'Advanced Spaceship Command': 20342,
    'Advanced Target Management': 3430,
    'Advanced Weapon Upgrades': 11207,
    'Afterburner': 3450,
    'Amarr Battlecruiser': 33095,
    'Amarr Battleship': 3339,
    'Amarr Carrier': 24311,
    'Amarr Core Systems': 30539,
    'Amarr Cruiser': 3335,
    'Amarr Defensive Systems': 30532,
    'Amarr Destroyer': 33091,
    'Amarr Dreadnought': 20525,
    'Amarr Drone Specialization': 12484,
    'Amarr Encryption Methods': 23087,
    'Amarr Fighter Specialization': 92397,
    'Amarr Freighter': 20524,
    'Amarr Frigate': 3331,
    'Amarr Hauler': 3343,
    'Amarr Offensive Systems': 30537,
    'Amarr Propulsion Systems': 30538,
    'Amarr Starship Engineering': 11444,
    'Amarr Strategic Cruiser': 30650,
    'Amarr Tactical Destroyer': 34390,
    'Amarr Titan': 3347,
    'Anchoring': 11584,
    'Archaeology': 13278,
    'Armor Layering': 33078,
    'Armor Rigging': 26253,
    'Armored Command': 20494,
    'Armored Command Specialist': 11569,
    'Assault Frigates': 12095,
    'Astrogeology': 3410,
    'Astrometric Acquisition': 25811,
    'Astrometric Pinpointing': 25810,
    'Astrometric Rangefinding': 25739,
    'Astrometrics': 3412,
    'Astronautic Engineering': 11487,
    'Astronautics Rigging': 26254,
    'Auto-Targeting Missiles': 3322,
    'Biology': 3405,
    'Black Ops': 28656,
    'Bomb Deployment': 28073,
    'Breacher Pod Clone Efficacity': 86261,
    'Breacher Pod Clone Longevity': 86262,
    'Breacher Pod Launcher Operation': 86260,
    'Breacher Pod Projection': 86263,
    'Breacher Pod Rapid Firing': 86264,
    'Broker Relations': 3446,
    'Burst Projector Operation': 27911,
    'CPU Management': 3426,
    'Caldari Battlecruiser': 33096,
    'Caldari Battleship': 3338,
    'Caldari Carrier': 24312,
    'Caldari Core Systems': 30548,
    'Caldari Cruiser': 3334,
    'Caldari Defensive Systems': 30544,
    'Caldari Destroyer': 33092,
    'Caldari Dreadnought': 20530,
    'Caldari Drone Specialization': 12487,
    'Caldari Encryption Methods': 21790,
    'Caldari Fighter Specialization': 92400,
    'Caldari Freighter': 20526,
    'Caldari Frigate': 3330,
    'Caldari Hauler': 3342,
    'Caldari Offensive Systems': 30549,
    'Caldari Propulsion Systems': 30552,
    'Caldari Starship Engineering': 11454,
    'Caldari Strategic Cruiser': 30651,
    'Caldari Tactical Destroyer': 35680,
    'Caldari Titan': 3346,
    'Capacitor Emission Systems': 3423,
    'Capacitor Management': 3418,
    'Capacitor Systems Operation': 3417,
    'Capital Artillery Specialization': 41404,
    'Capital Autocannon Specialization': 41403,
    'Capital Beam Laser Specialization': 41408,
    'Capital Blaster Specialization': 41405,
    'Capital Capacitor Emission Systems': 24572,
    'Capital Disintegrator Specialization': 92541,
    'Capital Energy Turret': 20327,
    'Capital Hybrid Turret': 21666,
    'Capital Industrial Reconfiguration': 28585,
    'Capital Industrial Ships': 28374,
    'Capital Jump Portal Generation': 83094,
    'Capital Micro Jump Drive Operation': 83464,
    'Capital Precursor Weapon': 52998,
    'Capital Projectile Turret': 21667,
    'Capital Pulse Laser Specialization': 41407,
    'Capital Railgun Specialization': 41406,
    'Capital Remote Armor Repair Systems': 24568,
    'Capital Remote Hull Repair Systems': 27936,
    'Capital Repair Systems': 21803,
    'Capital Shield Emission Systems': 24571,
    'Capital Shield Operation': 21802,
    'Capital Ship Construction': 22242,
    'Capital Shipboard Compression Technology': 62451,
    'Capital Ships': 20533,
    'Cloaking': 11579,
    'Cloning Facility Operation': 24606,
    'Coherent Ore Processing': 60378,
    'Command Burst Specialist': 3354,
    'Command Carriers': 93983,
    'Command Center Upgrades': 2505,
    'Command Destroyers': 37615,
    'Command Ships': 23950,
    'Common Moon Ore Processing': 46153,
    'Complex Ore Processing': 60380,
    'Connections': 3359,
    'Contracting': 25235,
    'Controlled Bursts': 3316,
    'Core Subsystem Technology': 30325,
    'Corporation Contracting': 25233,
    'Covert Ops': 12093,
    'Criminal Connections': 3361,
    'Cruise Missile Specialization': 20212,
    'Cruise Missiles': 3326,
    'Customs Code Expertise': 33467,
    'Cybernetics': 3411,
    'Cynosural Field Theory': 21603,
    'Daytrading': 16595,
    'Deep Core Mining': 11395,
    'Defender Missiles': 3323,
    'Defensive Subsystem Technology': 30324,
    'Diplomacy': 3357,
    'Disruptive Lance Operation': 77739,
    'Distribution Connections': 3894,
    'Doomsday Operation': 24563,
    'Doomsday Rapid Firing': 41537,
    'Drone Avionics': 3437,
    'Drone Durability': 23618,
    'Drone Interfacing': 3442,
    'Drone Navigation': 12305,
    'Drone Sharpshooting': 23606,
    'Drones': 3436,
    'Drones Rigging': 26255,
    'Drug Manufacturing': 26224,
    'EDENCOM Battleship': 54794,
    'EDENCOM Cruiser': 55032,
    'EDENCOM Frigate': 55031,
    'EM Armor Compensation': 22806,
    'EM Shield Compensation': 12365,
    'Electromagnetic Physics': 11448,
    'Electronic Attack Ships': 28615,
    'Electronic Engineering': 11453,
    'Electronic Superiority Rigging': 26256,
    'Electronic Warfare': 3427,
    'Electronics Upgrades': 3432,
    'Elite Infomorph Psychology': 73910,
    'Energy Grid Upgrades': 3424,
    'Energy Pulse Weapons': 3421,
    'Energy Weapon Rigging': 26258,
    'Erratic Ore Processing': 90040,
    'Evasive Maneuvering': 3453,
    'Exceptional Moon Ore Processing': 46156,
    'Exhumers': 22551,
    'Expedition Command': 89611,
    'Expedition Command Ships': 89609,
    'Expedition Command Specialist': 89610,
    'Expedition Frigates': 33856,
    'Explosive Armor Compensation': 22807,
    'Explosive Shield Compensation': 12367,
    'Fast Talk': 3358,
    'Fighter Hangar Management': 24613,
    'Fighters': 23069,
    'Fleet Command': 24764,
    'Fleet Compression Logistics': 62453,
    'Fleet Coordination': 57318,
    'Fleet Formations': 57317,
    'Freelancing': 91017,
    'Frequency Modulation': 19760,
    'Fuel Conservation': 3451,
    'Gallente Battlecruiser': 33097,
    'Gallente Battleship': 3336,
    'Gallente Carrier': 24313,
    'Gallente Core Systems': 30546,
    'Gallente Cruiser': 3332,
    'Gallente Defensive Systems': 30540,
    'Gallente Destroyer': 33093,
    'Gallente Dreadnought': 20531,
    'Gallente Drone Specialization': 12486,
    'Gallente Encryption Methods': 23121,
    'Gallente Fighter Specialization': 92398,
    'Gallente Freighter': 20527,
    'Gallente Frigate': 3328,
    'Gallente Hauler': 3340,
    'Gallente Offensive Systems': 30550,
    'Gallente Propulsion Systems': 30553,
    'Gallente Starship Engineering': 11450,
    'Gallente Strategic Cruiser': 30652,
    'Gallente Tactical Destroyer': 35685,
    'Gallente Titan': 3344,
    'Gas Cloud Harvesting': 25544,
    'Gas Decompression Efficiency': 62452,
    'Gravimetric Sensor Compensation': 33000,
    'Graviton Physics': 11446,
    'Guided Missile Precision': 20312,
    'Gunnery': 3300,
    'Hacking': 21718,
    'Heavy Assault Cruisers': 16591,
    'Heavy Assault Missile Specialization': 25718,
    'Heavy Assault Missiles': 25719,
    'Heavy Drone Operation': 3441,
    'Heavy Fighters': 32339,
    'Heavy Interdiction Cruisers': 28609,
    'Heavy Missile Specialization': 20211,
    'Heavy Missiles': 3324,
    'High Energy Physics': 11433,
    'High Speed Maneuvering': 3454,
    'Hull Upgrades': 3394,
    'Hybrid Weapon Rigging': 26259,
    'Hydromagnetic Physics': 11443,
    'Ice Harvesting': 16281,
    'Ice Harvesting Drone Operation': 43702,
    'Ice Harvesting Drone Specialization': 43703,
    'Ice Processing': 18025,
    'Industrial Command Ships': 29637,
    'Industrial Reconfiguration': 58956,
    'Industry': 3380,
    'Infomorph Psychology': 24242,
    'Infomorph Synchronizing': 33399,
    'Information Command': 20495,
    'Information Command Specialist': 3352,
    'Interceptors': 12092,
    'Interdictors': 12098,
    'Interplanetary Consolidation': 2495,
    'Invulnerability Core Operation': 44067,
    'Jump Drive Calibration': 21611,
    'Jump Drive Operation': 3456,
    'Jump Freighters': 29029,
    'Jump Fuel Conservation': 21610,
    'Jump Portal Generation': 24562,
    'Jury Rigging': 26252,
    'Kinetic Armor Compensation': 22808,
    'Kinetic Shield Compensation': 12366,
    'Laboratory Operation': 3406,
    'Ladar Sensor Compensation': 33001,
    'Lancer Dreadnoughts': 77738,
    'Large Artillery Specialization': 12203,
    'Large Autocannon Specialization': 12209,
    'Large Beam Laser Specialization': 12205,
    'Large Blaster Specialization': 12212,
    'Large Disintegrator Specialization': 47875,
    'Large Energy Turret': 3309,
    'Large Hybrid Turret': 3307,
    'Large Precursor Weapon': 47872,
    'Large Projectile Turret': 3308,
    'Large Pulse Laser Specialization': 12215,
    'Large Railgun Specialization': 12207,
    'Large Vorton Projector': 54826,
    'Large Vorton Specialization': 54829,
    'Laser Physics': 11447,
    'Launcher Rigging': 26260,
    'Leadership': 3348,
    'Light Drone Operation': 24241,
    'Light Fighters': 40572,
    'Light Missile Specialization': 20210,
    'Light Missiles': 3321,
    'Logistics Cruisers': 12096,
    'Logistics Frigates': 40328,
    'Long Distance Jamming': 19759,
    'Long Range Targeting': 3428,
    'Magnetometric Sensor Compensation': 32999,
    'Marauders': 28667,
    'Marketing': 16598,
    'Mass Production': 3387,
    'Mass Reactions': 45748,
    'Mechanical Engineering': 11452,
    'Mechanics': 3392,
    'Medium Artillery Specialization': 12202,
    'Medium Autocannon Specialization': 12208,
    'Medium Beam Laser Specialization': 12204,
    'Medium Blaster Specialization': 12211,
    'Medium Disintegrator Specialization': 47874,
    'Medium Drone Operation': 33699,
    'Medium Energy Turret': 3306,
    'Medium Hybrid Turret': 3304,
    'Medium Precursor Weapon': 47871,
    'Medium Projectile Turret': 3305,
    'Medium Pulse Laser Specialization': 12214,
    'Medium Railgun Specialization': 12206,
    'Medium Vorton Projector': 55035,
    'Medium Vorton Specialization': 54828,
    'Mercoxit Ore Processing': 12189,
    'Metallurgy': 3409,
    'Micro Jump Drive Operation': 4385,
    'Mining': 3386,
    'Mining Barge': 17940,
    'Mining Connections': 3893,
    'Mining Destroyer': 89241,
    'Mining Director': 22552,
    'Mining Drone Operation': 3438,
    'Mining Drone Specialization': 22541,
    'Mining Exploitation': 90728,
    'Mining Foreman': 22536,
    'Mining Frigate': 32918,
    'Mining Precision': 90727,
    'Mining Upgrades': 22578,
    'Minmatar Battlecruiser': 33098,
    'Minmatar Battleship': 3337,
    'Minmatar Carrier': 24314,
    'Minmatar Core Systems': 30547,
    'Minmatar Cruiser': 3333,
    'Minmatar Defensive Systems': 30545,
    'Minmatar Destroyer': 33094,
    'Minmatar Dreadnought': 20532,
    'Minmatar Drone Specialization': 12485,
    'Minmatar Encryption Methods': 21791,
    'Minmatar Fighter Specialization': 92399,
    'Minmatar Freighter': 20528,
    'Minmatar Frigate': 3329,
    'Minmatar Hauler': 3341,
    'Minmatar Offensive Systems': 30551,
    'Minmatar Propulsion Systems': 30554,
    'Minmatar Starship Engineering': 11445,
    'Minmatar Strategic Cruiser': 30653,
    'Minmatar Tactical Destroyer': 34533,
    'Minmatar Titan': 3345,
    'Missile Bombardment': 12441,
    'Missile Launcher Operation': 3319,
    'Missile Projection': 12442,
    'Molecular Engineering': 11529,
    'Motion Prediction': 3312,
    'Mutagenic Stabilization': 81896,
    'Mutated Drone Specialization': 60515,
    'Nanite Engineering': 11442,
    'Nanite Interfacing': 28880,
    'Nanite Operation': 28879,
    'Navigation': 3449,
    'Negotiation': 3356,
    'Neurotoxin Control': 25538,
    'Neurotoxin Recovery': 25530,
    'Nuclear Physics': 11451,
    'ORE Freighter': 34327,
    'ORE Hauler': 3184,
    'Offensive Subsystem Technology': 30327,
    'Outpost Construction': 3400,
    'Planetology': 2406,
    'Plasma Physics': 11441,
    'Power Grid Management': 3413,
    'Precursor Battlecruiser': 49743,
    'Precursor Battleship': 47869,
    'Precursor Cruiser': 47868,
    'Precursor Destroyer': 49742,
    'Precursor Dreadnought': 52997,
    'Precursor Frigate': 47867,
    'Procurement': 16594,
    'Projectile Weapon Rigging': 26257,
    'Propulsion Jamming': 3435,
    'Propulsion Subsystem Technology': 30788,
    'Quantum Physics': 11455,
    'Radar Sensor Compensation': 33002,
    'Rapid Firing': 3310,
    'Rapid Launch': 21071,
    'Rare Moon Ore Processing': 46155,
    'Reactions': 45746,
    'Recon Ships': 22761,
    'Remote Armor Repair Systems': 16069,
    'Remote Hull Repair Systems': 27902,
    'Remote Reactions': 45750,
    'Remote Sensing': 13279,
    'Repair Drone Operation': 3439,
    'Repair Systems': 3393,
    'Reprocessing': 3385,
    'Reprocessing Efficiency': 3389,
    'Research': 3403,
    'Research Project Management': 12179,
    'Resistance Phasing': 32797,
    'Retail': 3444,
    'Rocket Science': 11449,
    'Rocket Specialization': 20209,
    'Rockets': 3320,
    'Salvage Drone Operation': 3440,
    'Salvage Drone Specialization': 57164,
    'Salvaging': 25863,
    'Science': 3402,
    'Scientific Networking': 24270,
    'Scrapmetal Processing': 12196,
    'Security Connections': 3895,
    'Sensor Linking': 3433,
    'Sentry Drone Interfacing': 23594,
    'Sharpshooter': 3311,
    'Shield Command': 3350,
    'Shield Command Specialist': 3351,
    'Shield Compensation': 21059,
    'Shield Emission Systems': 3422,
    'Shield Management': 3419,
    'Shield Operation': 3416,
    'Shield Rigging': 26261,
    'Shield Upgrades': 3425,
    'Shipboard Compression Technology': 62450,
    'Signal Dispersion': 19761,
    'Signal Suppression': 19766,
    'Signature Analysis': 3431,
    'Signature Focusing': 19922,
    'Signature Masking': 4411,
    'Simple Ore Processing': 60377,
    'Skirmish Command': 3349,
    'Skirmish Command Specialist': 11572,
    'Sleeper Encryption Methods': 3408,
    'Sleeper Technology': 21789,
    'Small Artillery Specialization': 12201,
    'Small Autocannon Specialization': 11084,
    'Small Beam Laser Specialization': 11083,
    'Small Blaster Specialization': 12210,
    'Small Disintegrator Specialization': 47873,
    'Small Energy Turret': 3303,
    'Small Hybrid Turret': 3301,
    'Small Precursor Weapon': 47870,
    'Small Projectile Turret': 3302,
    'Small Pulse Laser Specialization': 12213,
    'Small Railgun Specialization': 11082,
    'Small Vorton Projector': 55034,
    'Small Vorton Specialization': 54827,
    'Social': 3355,
    'Spaceship Command': 3327,
    'Spatial Phenomena Generation': 43728,
    'Supply Chain Management': 24268,
    'Support Fighters': 40573,
    'Surgical Strike': 3315,
    'Survey': 3551,
    'Tactical Logistics Reconfiguration': 27906,
    'Tactical Shield Manipulation': 3420,
    'Tactical Weapon Reconfiguration': 22043,
    'Takmahl Technology': 23123,
    'Talocan Technology': 20433,
    'Target Management': 3429,
    'Target Navigation Prediction': 20314,
    'Target Painting': 19921,
    'Thermal Armor Compensation': 22809,
    'Thermal Shield Compensation': 11566,
    'Thermodynamics': 28164,
    'Torpedo Specialization': 20213,
    'Torpedoes': 3325,
    'Trade': 3443,
    'Trajectory Analysis': 3317,
    'Transport Ships': 19719,
    'Triglavian Encryption Methods': 52308,
    'Triglavian Quantum Engineering': 52307,
    'Tycoon': 18580,
    'Ubiquitous Moon Ore Processing': 46152,
    'Uncommon Moon Ore Processing': 46154,
    'Unrefined Minerals Processing': 90398,
    'Upwell Encryption Methods': 55025,
    'Upwell Freighter': 81044,
    'Upwell Hauler': 81032,
    'Upwell Starship Engineering': 81050,
    'Variegated Ore Processing': 60379,
    'Visibility': 3447,
    'Vorton Arc Extension': 55511,
    'Vorton Arc Guidance': 54841,
    'Vorton Power Amplification': 54840,
    'Vorton Projector Operation': 55033,
    'Warhead Upgrades': 20315,
    'Warp Drive Operation': 3455,
    'Weapon Destabilization': 19767,
    'Weapon Disruption': 3434,
    'Weapon Upgrades': 3318,
    'Wholesale': 16596,
    'Wing Command': 11574,
    'XL Cruise Missile Specialization': 41410,
    'XL Cruise Missiles': 32435,
    'XL Torpedo Specialization': 41409,
    'XL Torpedoes': 21668,
    'Yan Jung Technology': 23124,
}

FULL_SKILL_NAMES = {
    'Exploration': [
        'Archaeology',
        'Astrometric Acquisition',
        'Astrometric Pinpointing',
        'Astrometric Rangefinding',
        'Astrometrics',
        'Hacking',
        'Survey',
    ],
    'Mining': [
        'Abyssal Ore Processing',
        'Advanced Mass Reactions',
        'Astrogeology',
        'CPU Management',
        'Capacitor Management',
        'Capacitor Systems Operation',
        'Capital Industrial Reconfiguration',
        'Capital Shipboard Compression Technology',
        'Coherent Ore Processing',
        'Common Moon Ore Processing',
        'Complex Ore Processing',
        'Deep Core Mining',
        'Erratic Ore Processing',
        'Evasive Maneuvering',
        'Exceptional Moon Ore Processing',
        'Exhumers',
        'Gas Cloud Harvesting',
        'Gas Decompression Efficiency',
        'Hull Upgrades',
        'Ice Harvesting',
        'Ice Harvesting Drone Operation',
        'Ice Harvesting Drone Specialization',
        'Ice Processing',
        'Industrial Reconfiguration',
        'Long Range Targeting',
        'Mass Reactions',
        'Mechanics',
        'Mercoxit Ore Processing',
        'Mining',
        'Mining Barge',
        'Mining Connections',
        'Mining Destroyer',
        'Mining Director',
        'Mining Drone Operation',
        'Mining Drone Specialization',
        'Mining Exploitation',
        'Mining Foreman',
        'Mining Frigate',
        'Mining Precision',
        'Mining Upgrades',
        'Navigation',
        'Power Grid Management',
        'Rare Moon Ore Processing',
        'Reactions',
        'Remote Reactions',
        'Reprocessing',
        'Reprocessing Efficiency',
        'Salvaging',
        'Scrapmetal Processing',
        'Shield Management',
        'Shield Operation',
        'Shipboard Compression Technology',
        'Signature Analysis',
        'Simple Ore Processing',
        'Spaceship Command',
        'Ubiquitous Moon Ore Processing',
        'Uncommon Moon Ore Processing',
        'Unrefined Minerals Processing',
        'Variegated Ore Processing',
        'Warp Drive Operation',
    ],
    'Industry': [
        'Abyssal Ore Processing',
        'Accounting',
        'Advanced Broker Relations',
        'Advanced Capital Ship Construction',
        'Advanced Industrial Ship Construction',
        'Advanced Industry',
        'Advanced Laboratory Operation',
        'Advanced Large Ship Construction',
        'Advanced Mass Production',
        'Advanced Mass Reactions',
        'Advanced Medium Ship Construction',
        'Advanced Planetology',
        'Advanced Small Ship Construction',
        'Amarr Encryption Methods',
        'Amarr Starship Engineering',
        'Astrogeology',
        'Astronautic Engineering',
        'Broker Relations',
        'Caldari Encryption Methods',
        'Caldari Starship Engineering',
        'Capital Industrial Reconfiguration',
        'Capital Ship Construction',
        'Capital Shipboard Compression Technology',
        'Coherent Ore Processing',
        'Command Center Upgrades',
        'Common Moon Ore Processing',
        'Complex Ore Processing',
        'Core Subsystem Technology',
        'Deep Core Mining',
        'Defensive Subsystem Technology',
        'Drug Manufacturing',
        'Electromagnetic Physics',
        'Electronic Engineering',
        'Erratic Ore Processing',
        'Exceptional Moon Ore Processing',
        'Gallente Encryption Methods',
        'Gallente Starship Engineering',
        'Gas Cloud Harvesting',
        'Gas Decompression Efficiency',
        'Graviton Physics',
        'High Energy Physics',
        'Hydromagnetic Physics',
        'Ice Harvesting',
        'Ice Processing',
        'Industrial Reconfiguration',
        'Industry',
        'Interplanetary Consolidation',
        'Laboratory Operation',
        'Laser Physics',
        'Mass Production',
        'Mass Reactions',
        'Mechanical Engineering',
        'Mercoxit Ore Processing',
        'Metallurgy',
        'Mining',
        'Mining Exploitation',
        'Mining Precision',
        'Mining Upgrades',
        'Minmatar Encryption Methods',
        'Minmatar Starship Engineering',
        'Molecular Engineering',
        'Mutagenic Stabilization',
        'Nanite Engineering',
        'Nuclear Physics',
        'Offensive Subsystem Technology',
        'Outpost Construction',
        'Planetology',
        'Plasma Physics',
        'Propulsion Subsystem Technology',
        'Quantum Physics',
        'Rare Moon Ore Processing',
        'Reactions',
        'Remote Reactions',
        'Remote Sensing',
        'Reprocessing',
        'Reprocessing Efficiency',
        'Research',
        'Research Project Management',
        'Rocket Science',
        'Salvaging',
        'Science',
        'Scientific Networking',
        'Scrapmetal Processing',
        'Shipboard Compression Technology',
        'Simple Ore Processing',
        'Sleeper Encryption Methods',
        'Sleeper Technology',
        'Supply Chain Management',
        'Takmahl Technology',
        'Talocan Technology',
        'Triglavian Encryption Methods',
        'Triglavian Quantum Engineering',
        'Ubiquitous Moon Ore Processing',
        'Uncommon Moon Ore Processing',
        'Unrefined Minerals Processing',
        'Upwell Encryption Methods',
        'Upwell Starship Engineering',
        'Variegated Ore Processing',
        'Yan Jung Technology',
    ],
    'Mission Running': [
        'Advanced Armor Layering',
        'Advanced Doomsday Operation',
        'Advanced Drone Avionics',
        'Advanced Spaceship Command',
        'Advanced Target Management',
        'Amarr Battlecruiser',
        'Amarr Battleship',
        'Amarr Carrier',
        'Amarr Core Systems',
        'Amarr Cruiser',
        'Amarr Defensive Systems',
        'Amarr Destroyer',
        'Amarr Dreadnought',
        'Amarr Drone Specialization',
        'Amarr Fighter Specialization',
        'Amarr Freighter',
        'Amarr Frigate',
        'Amarr Hauler',
        'Amarr Offensive Systems',
        'Amarr Propulsion Systems',
        'Amarr Strategic Cruiser',
        'Amarr Tactical Destroyer',
        'Amarr Titan',
        'Armor Layering',
        'Armor Rigging',
        'Assault Frigates',
        'Astronautics Rigging',
        'Auto-Targeting Missiles',
        'Black Ops',
        'Bomb Deployment',
        'Breacher Pod Clone Efficacity',
        'Breacher Pod Clone Longevity',
        'Breacher Pod Launcher Operation',
        'Breacher Pod Projection',
        'Breacher Pod Rapid Firing',
        'Caldari Battlecruiser',
        'Caldari Battleship',
        'Caldari Carrier',
        'Caldari Core Systems',
        'Caldari Cruiser',
        'Caldari Defensive Systems',
        'Caldari Destroyer',
        'Caldari Dreadnought',
        'Caldari Drone Specialization',
        'Caldari Fighter Specialization',
        'Caldari Freighter',
        'Caldari Frigate',
        'Caldari Hauler',
        'Caldari Offensive Systems',
        'Caldari Propulsion Systems',
        'Caldari Strategic Cruiser',
        'Caldari Tactical Destroyer',
        'Caldari Titan',
        'Capital Artillery Specialization',
        'Capital Autocannon Specialization',
        'Capital Beam Laser Specialization',
        'Capital Blaster Specialization',
        'Capital Disintegrator Specialization',
        'Capital Energy Turret',
        'Capital Hybrid Turret',
        'Capital Industrial Ships',
        'Capital Precursor Weapon',
        'Capital Projectile Turret',
        'Capital Pulse Laser Specialization',
        'Capital Railgun Specialization',
        'Capital Remote Armor Repair Systems',
        'Capital Remote Hull Repair Systems',
        'Capital Repair Systems',
        'Capital Shield Emission Systems',
        'Capital Shield Operation',
        'Capital Ships',
        'Command Carriers',
        'Command Destroyers',
        'Command Ships',
        'Connections',
        'Controlled Bursts',
        'Covert Ops',
        'Criminal Connections',
        'Cruise Missile Specialization',
        'Cruise Missiles',
        'Defender Missiles',
        'Diplomacy',
        'Disruptive Lance Operation',
        'Distribution Connections',
        'Doomsday Operation',
        'Doomsday Rapid Firing',
        'Drone Avionics',
        'Drone Durability',
        'Drone Interfacing',
        'Drone Navigation',
        'Drone Sharpshooting',
        'Drones',
        'Drones Rigging',
        'EM Armor Compensation',
        'EM Shield Compensation',
        'Electronic Attack Ships',
        'Electronic Superiority Rigging',
        'Energy Weapon Rigging',
        'Expedition Command Ships',
        'Expedition Frigates',
        'Explosive Armor Compensation',
        'Explosive Shield Compensation',
        'Fast Talk',
        'Fighter Hangar Management',
        'Fighters',
        'Freelancing',
        'Gallente Battlecruiser',
        'Gallente Battleship',
        'Gallente Carrier',
        'Gallente Core Systems',
        'Gallente Cruiser',
        'Gallente Defensive Systems',
        'Gallente Destroyer',
        'Gallente Dreadnought',
        'Gallente Drone Specialization',
        'Gallente Fighter Specialization',
        'Gallente Freighter',
        'Gallente Frigate',
        'Gallente Hauler',
        'Gallente Offensive Systems',
        'Gallente Propulsion Systems',
        'Gallente Strategic Cruiser',
        'Gallente Tactical Destroyer',
        'Gallente Titan',
        'Gravimetric Sensor Compensation',
        'Guided Missile Precision',
        'Gunnery',
        'Heavy Assault Cruisers',
        'Heavy Assault Missile Specialization',
        'Heavy Assault Missiles',
        'Heavy Drone Operation',
        'Heavy Fighters',
        'Heavy Interdiction Cruisers',
        'Heavy Missile Specialization',
        'Heavy Missiles',
        'Hull Upgrades',
        'Hybrid Weapon Rigging',
        'Industrial Command Ships',
        'Interceptors',
        'Interdictors',
        'Invulnerability Core Operation',
        'Jump Freighters',
        'Kinetic Armor Compensation',
        'Kinetic Shield Compensation',
        'Ladar Sensor Compensation',
        'Lancer Dreadnoughts',
        'Large Artillery Specialization',
        'Large Autocannon Specialization',
        'Large Beam Laser Specialization',
        'Large Blaster Specialization',
        'Large Disintegrator Specialization',
        'Large Energy Turret',
        'Large Hybrid Turret',
        'Large Precursor Weapon',
        'Large Projectile Turret',
        'Large Pulse Laser Specialization',
        'Large Railgun Specialization',
        'Large Vorton Projector',
        'Large Vorton Specialization',
        'Launcher Rigging',
        'Light Drone Operation',
        'Light Fighters',
        'Light Missile Specialization',
        'Light Missiles',
        'Logistics Cruisers',
        'Logistics Frigates',
        'Long Range Targeting',
        'Magnetometric Sensor Compensation',
        'Marauders',
        'Mechanics',
        'Medium Artillery Specialization',
        'Medium Autocannon Specialization',
        'Medium Beam Laser Specialization',
        'Medium Blaster Specialization',
        'Medium Disintegrator Specialization',
        'Medium Drone Operation',
        'Medium Energy Turret',
        'Medium Hybrid Turret',
        'Medium Precursor Weapon',
        'Medium Projectile Turret',
        'Medium Pulse Laser Specialization',
        'Medium Railgun Specialization',
        'Medium Vorton Projector',
        'Medium Vorton Specialization',
        'Mining Connections',
        'Minmatar Battlecruiser',
        'Minmatar Battleship',
        'Minmatar Carrier',
        'Minmatar Core Systems',
        'Minmatar Cruiser',
        'Minmatar Defensive Systems',
        'Minmatar Destroyer',
        'Minmatar Dreadnought',
        'Minmatar Drone Specialization',
        'Minmatar Fighter Specialization',
        'Minmatar Freighter',
        'Minmatar Frigate',
        'Minmatar Hauler',
        'Minmatar Offensive Systems',
        'Minmatar Propulsion Systems',
        'Minmatar Strategic Cruiser',
        'Minmatar Tactical Destroyer',
        'Minmatar Titan',
        'Missile Bombardment',
        'Missile Launcher Operation',
        'Missile Projection',
        'Motion Prediction',
        'Mutated Drone Specialization',
        'Negotiation',
        'ORE Freighter',
        'ORE Hauler',
        'Projectile Weapon Rigging',
        'Radar Sensor Compensation',
        'Rapid Firing',
        'Rapid Launch',
        'Recon Ships',
        'Remote Armor Repair Systems',
        'Remote Hull Repair Systems',
        'Repair Drone Operation',
        'Repair Systems',
        'Rocket Specialization',
        'Rockets',
        'Salvage Drone Operation',
        'Salvage Drone Specialization',
        'Security Connections',
        'Sentry Drone Interfacing',
        'Sharpshooter',
        'Shield Compensation',
        'Shield Emission Systems',
        'Shield Management',
        'Shield Operation',
        'Shield Rigging',
        'Shield Upgrades',
        'Signature Analysis',
        'Small Artillery Specialization',
        'Small Autocannon Specialization',
        'Small Beam Laser Specialization',
        'Small Blaster Specialization',
        'Small Disintegrator Specialization',
        'Small Energy Turret',
        'Small Hybrid Turret',
        'Small Precursor Weapon',
        'Small Projectile Turret',
        'Small Pulse Laser Specialization',
        'Small Railgun Specialization',
        'Small Vorton Projector',
        'Small Vorton Specialization',
        'Social',
        'Spaceship Command',
        'Support Fighters',
        'Surgical Strike',
        'Tactical Shield Manipulation',
        'Tactical Weapon Reconfiguration',
        'Target Management',
        'Target Navigation Prediction',
        'Thermal Armor Compensation',
        'Thermal Shield Compensation',
        'Torpedo Specialization',
        'Torpedoes',
        'Trajectory Analysis',
        'Transport Ships',
        'Upwell Freighter',
        'Upwell Hauler',
        'Vorton Arc Extension',
        'Vorton Arc Guidance',
        'Vorton Power Amplification',
        'Vorton Projector Operation',
        'Warhead Upgrades',
        'XL Cruise Missile Specialization',
        'XL Cruise Missiles',
        'XL Torpedo Specialization',
        'XL Torpedoes',
    ],
    'PVP': [
        'Acceleration Control',
        'Advanced Armor Layering',
        'Advanced Doomsday Operation',
        'Advanced Drone Avionics',
        'Advanced Spaceship Command',
        'Advanced Target Management',
        'Afterburner',
        'Amarr Battlecruiser',
        'Amarr Battleship',
        'Amarr Carrier',
        'Amarr Core Systems',
        'Amarr Cruiser',
        'Amarr Defensive Systems',
        'Amarr Destroyer',
        'Amarr Dreadnought',
        'Amarr Drone Specialization',
        'Amarr Fighter Specialization',
        'Amarr Freighter',
        'Amarr Frigate',
        'Amarr Hauler',
        'Amarr Offensive Systems',
        'Amarr Propulsion Systems',
        'Amarr Strategic Cruiser',
        'Amarr Tactical Destroyer',
        'Amarr Titan',
        'Armor Layering',
        'Armor Rigging',
        'Armored Command',
        'Armored Command Specialist',
        'Assault Frigates',
        'Astronautics Rigging',
        'Auto-Targeting Missiles',
        'Black Ops',
        'Bomb Deployment',
        'Breacher Pod Clone Efficacity',
        'Breacher Pod Clone Longevity',
        'Breacher Pod Launcher Operation',
        'Breacher Pod Projection',
        'Breacher Pod Rapid Firing',
        'Burst Projector Operation',
        'CPU Management',
        'Caldari Battlecruiser',
        'Caldari Battleship',
        'Caldari Carrier',
        'Caldari Core Systems',
        'Caldari Cruiser',
        'Caldari Defensive Systems',
        'Caldari Destroyer',
        'Caldari Dreadnought',
        'Caldari Drone Specialization',
        'Caldari Fighter Specialization',
        'Caldari Freighter',
        'Caldari Frigate',
        'Caldari Hauler',
        'Caldari Offensive Systems',
        'Caldari Propulsion Systems',
        'Caldari Strategic Cruiser',
        'Caldari Tactical Destroyer',
        'Caldari Titan',
        'Capacitor Management',
        'Capacitor Systems Operation',
        'Capital Artillery Specialization',
        'Capital Autocannon Specialization',
        'Capital Beam Laser Specialization',
        'Capital Blaster Specialization',
        'Capital Disintegrator Specialization',
        'Capital Energy Turret',
        'Capital Hybrid Turret',
        'Capital Industrial Ships',
        'Capital Jump Portal Generation',
        'Capital Micro Jump Drive Operation',
        'Capital Precursor Weapon',
        'Capital Projectile Turret',
        'Capital Pulse Laser Specialization',
        'Capital Railgun Specialization',
        'Capital Remote Armor Repair Systems',
        'Capital Remote Hull Repair Systems',
        'Capital Repair Systems',
        'Capital Shield Emission Systems',
        'Capital Shield Operation',
        'Capital Ships',
        'Cloaking',
        'Command Burst Specialist',
        'Command Carriers',
        'Command Destroyers',
        'Command Ships',
        'Controlled Bursts',
        'Covert Ops',
        'Criminal Connections',
        'Cruise Missile Specialization',
        'Cruise Missiles',
        'Cynosural Field Theory',
        'Defender Missiles',
        'Disruptive Lance Operation',
        'Doomsday Operation',
        'Doomsday Rapid Firing',
        'Drone Avionics',
        'Drone Durability',
        'Drone Interfacing',
        'Drone Navigation',
        'Drone Sharpshooting',
        'Drones',
        'Drones Rigging',
        'EDENCOM Battleship',
        'EDENCOM Cruiser',
        'EDENCOM Frigate',
        'EM Armor Compensation',
        'EM Shield Compensation',
        'Electronic Attack Ships',
        'Electronic Superiority Rigging',
        'Electronic Warfare',
        'Energy Weapon Rigging',
        'Evasive Maneuvering',
        'Expedition Command',
        'Expedition Command Ships',
        'Expedition Command Specialist',
        'Expedition Frigates',
        'Explosive Armor Compensation',
        'Explosive Shield Compensation',
        'Fast Talk',
        'Fighter Hangar Management',
        'Fighters',
        'Fleet Command',
        'Fleet Compression Logistics',
        'Fleet Coordination',
        'Fleet Formations',
        'Frequency Modulation',
        'Fuel Conservation',
        'Gallente Battlecruiser',
        'Gallente Battleship',
        'Gallente Carrier',
        'Gallente Core Systems',
        'Gallente Cruiser',
        'Gallente Defensive Systems',
        'Gallente Destroyer',
        'Gallente Dreadnought',
        'Gallente Drone Specialization',
        'Gallente Fighter Specialization',
        'Gallente Freighter',
        'Gallente Frigate',
        'Gallente Hauler',
        'Gallente Offensive Systems',
        'Gallente Propulsion Systems',
        'Gallente Strategic Cruiser',
        'Gallente Tactical Destroyer',
        'Gallente Titan',
        'Gravimetric Sensor Compensation',
        'Guided Missile Precision',
        'Gunnery',
        'Heavy Assault Cruisers',
        'Heavy Assault Missile Specialization',
        'Heavy Assault Missiles',
        'Heavy Drone Operation',
        'Heavy Fighters',
        'Heavy Interdiction Cruisers',
        'Heavy Missile Specialization',
        'Heavy Missiles',
        'High Speed Maneuvering',
        'Hull Upgrades',
        'Hybrid Weapon Rigging',
        'Industrial Command Ships',
        'Information Command',
        'Information Command Specialist',
        'Interceptors',
        'Interdictors',
        'Invulnerability Core Operation',
        'Jump Drive Calibration',
        'Jump Drive Operation',
        'Jump Freighters',
        'Jump Fuel Conservation',
        'Jump Portal Generation',
        'Kinetic Armor Compensation',
        'Kinetic Shield Compensation',
        'Ladar Sensor Compensation',
        'Lancer Dreadnoughts',
        'Large Artillery Specialization',
        'Large Autocannon Specialization',
        'Large Beam Laser Specialization',
        'Large Blaster Specialization',
        'Large Disintegrator Specialization',
        'Large Energy Turret',
        'Large Hybrid Turret',
        'Large Precursor Weapon',
        'Large Projectile Turret',
        'Large Pulse Laser Specialization',
        'Large Railgun Specialization',
        'Large Vorton Projector',
        'Large Vorton Specialization',
        'Launcher Rigging',
        'Leadership',
        'Light Drone Operation',
        'Light Fighters',
        'Light Missile Specialization',
        'Light Missiles',
        'Logistics Cruisers',
        'Logistics Frigates',
        'Long Distance Jamming',
        'Long Range Targeting',
        'Magnetometric Sensor Compensation',
        'Marauders',
        'Mechanics',
        'Medium Artillery Specialization',
        'Medium Autocannon Specialization',
        'Medium Beam Laser Specialization',
        'Medium Blaster Specialization',
        'Medium Disintegrator Specialization',
        'Medium Drone Operation',
        'Medium Energy Turret',
        'Medium Hybrid Turret',
        'Medium Precursor Weapon',
        'Medium Projectile Turret',
        'Medium Pulse Laser Specialization',
        'Medium Railgun Specialization',
        'Medium Vorton Projector',
        'Medium Vorton Specialization',
        'Micro Jump Drive Operation',
        'Minmatar Battlecruiser',
        'Minmatar Battleship',
        'Minmatar Carrier',
        'Minmatar Core Systems',
        'Minmatar Cruiser',
        'Minmatar Defensive Systems',
        'Minmatar Destroyer',
        'Minmatar Dreadnought',
        'Minmatar Drone Specialization',
        'Minmatar Fighter Specialization',
        'Minmatar Freighter',
        'Minmatar Frigate',
        'Minmatar Hauler',
        'Minmatar Offensive Systems',
        'Minmatar Propulsion Systems',
        'Minmatar Strategic Cruiser',
        'Minmatar Tactical Destroyer',
        'Minmatar Titan',
        'Missile Bombardment',
        'Missile Launcher Operation',
        'Missile Projection',
        'Motion Prediction',
        'Mutated Drone Specialization',
        'Navigation',
        'ORE Freighter',
        'ORE Hauler',
        'Power Grid Management',
        'Precursor Battlecruiser',
        'Precursor Battleship',
        'Precursor Cruiser',
        'Precursor Destroyer',
        'Precursor Dreadnought',
        'Precursor Frigate',
        'Projectile Weapon Rigging',
        'Propulsion Jamming',
        'Radar Sensor Compensation',
        'Rapid Firing',
        'Rapid Launch',
        'Recon Ships',
        'Remote Armor Repair Systems',
        'Remote Hull Repair Systems',
        'Repair Drone Operation',
        'Repair Systems',
        'Rocket Specialization',
        'Rockets',
        'Salvage Drone Operation',
        'Salvage Drone Specialization',
        'Sensor Linking',
        'Sentry Drone Interfacing',
        'Sharpshooter',
        'Shield Command',
        'Shield Command Specialist',
        'Shield Compensation',
        'Shield Emission Systems',
        'Shield Management',
        'Shield Operation',
        'Shield Rigging',
        'Shield Upgrades',
        'Signal Dispersion',
        'Signal Suppression',
        'Signature Analysis',
        'Signature Focusing',
        'Signature Masking',
        'Skirmish Command',
        'Skirmish Command Specialist',
        'Small Artillery Specialization',
        'Small Autocannon Specialization',
        'Small Beam Laser Specialization',
        'Small Blaster Specialization',
        'Small Disintegrator Specialization',
        'Small Energy Turret',
        'Small Hybrid Turret',
        'Small Precursor Weapon',
        'Small Projectile Turret',
        'Small Pulse Laser Specialization',
        'Small Railgun Specialization',
        'Small Vorton Projector',
        'Small Vorton Specialization',
        'Spaceship Command',
        'Spatial Phenomena Generation',
        'Support Fighters',
        'Surgical Strike',
        'Tactical Logistics Reconfiguration',
        'Tactical Shield Manipulation',
        'Tactical Weapon Reconfiguration',
        'Target Management',
        'Target Navigation Prediction',
        'Target Painting',
        'Thermal Armor Compensation',
        'Thermal Shield Compensation',
        'Torpedo Specialization',
        'Torpedoes',
        'Trajectory Analysis',
        'Transport Ships',
        'Upwell Freighter',
        'Upwell Hauler',
        'Vorton Arc Extension',
        'Vorton Arc Guidance',
        'Vorton Power Amplification',
        'Vorton Projector Operation',
        'Warhead Upgrades',
        'Warp Drive Operation',
        'Weapon Destabilization',
        'Weapon Disruption',
        'Wing Command',
        'XL Cruise Missile Specialization',
        'XL Cruise Missiles',
        'XL Torpedo Specialization',
        'XL Torpedoes',
    ],
    'Quality of Life': [
        'Acceleration Control',
        'Accounting',
        'Advanced Broker Relations',
        'Advanced Contracting',
        'Advanced Infomorph Psychology',
        'Advanced Weapon Upgrades',
        'Afterburner',
        'Anchoring',
        'Archaeology',
        'Astrometric Acquisition',
        'Astrometric Pinpointing',
        'Astrometric Rangefinding',
        'Astrometrics',
        'Biology',
        'Broker Relations',
        'CPU Management',
        'Capacitor Emission Systems',
        'Capacitor Management',
        'Capacitor Systems Operation',
        'Capital Capacitor Emission Systems',
        'Capital Jump Portal Generation',
        'Capital Micro Jump Drive Operation',
        'Cloning Facility Operation',
        'Connections',
        'Contracting',
        'Corporation Contracting',
        'Criminal Connections',
        'Customs Code Expertise',
        'Cybernetics',
        'Cynosural Field Theory',
        'Daytrading',
        'Diplomacy',
        'Distribution Connections',
        'Electronics Upgrades',
        'Elite Infomorph Psychology',
        'Energy Grid Upgrades',
        'Energy Pulse Weapons',
        'Evasive Maneuvering',
        'Fast Talk',
        'Freelancing',
        'Fuel Conservation',
        'Hacking',
        'High Speed Maneuvering',
        'Infomorph Psychology',
        'Infomorph Synchronizing',
        'Jump Drive Calibration',
        'Jump Drive Operation',
        'Jump Fuel Conservation',
        'Jump Portal Generation',
        'Jury Rigging',
        'Marketing',
        'Micro Jump Drive Operation',
        'Mining Connections',
        'Nanite Interfacing',
        'Nanite Operation',
        'Navigation',
        'Negotiation',
        'Neurotoxin Control',
        'Neurotoxin Recovery',
        'Power Grid Management',
        'Procurement',
        'Resistance Phasing',
        'Retail',
        'Security Connections',
        'Social',
        'Survey',
        'Thermodynamics',
        'Trade',
        'Tycoon',
        'Visibility',
        'Warp Drive Operation',
        'Weapon Upgrades',
        'Wholesale',
    ],
}
