# Auto-generated: every skill in skill_categories_data.SKILL_TYPE_IDS,
# grouped by its REAL EVE skill group — resolved once via each skill's
# live group_id (/universe/types/{id}/) and that group's name
# (/universe/groups/{id}/), not the 6 curated playstyle categories used
# elsewhere. Do not hand-edit; regenerate via gen_skill_data.py instead if
# the game adds/removes skills. A group with zero surviving skills after a
# regeneration is dropped rather than kept as an empty dead end.

SKILL_GROUPS = {
    'Armor': ['Advanced Armor Layering', 'Armor Layering', 'Capital Remote Armor Repair Systems', 'Capital Remote Hull Repair Systems', 'Capital Repair Systems', 'EM Armor Compensation', 'Explosive Armor Compensation', 'Hull Upgrades', 'Kinetic Armor Compensation', 'Mechanics', 'Remote Armor Repair Systems', 'Remote Hull Repair Systems', 'Repair Systems', 'Thermal Armor Compensation'],
    'Drones': ['Advanced Drone Avionics', 'Amarr Drone Specialization', 'Amarr Fighter Specialization', 'Caldari Drone Specialization', 'Caldari Fighter Specialization', 'Drone Avionics', 'Drone Durability', 'Drone Interfacing', 'Drone Navigation', 'Drone Sharpshooting', 'Drones', 'Fighter Hangar Management', 'Fighters', 'Gallente Drone Specialization', 'Gallente Fighter Specialization', 'Heavy Drone Operation', 'Heavy Fighters', 'Ice Harvesting Drone Operation', 'Ice Harvesting Drone Specialization', 'Light Drone Operation', 'Light Fighters', 'Medium Drone Operation', 'Mining Drone Operation', 'Mining Drone Specialization', 'Minmatar Drone Specialization', 'Minmatar Fighter Specialization', 'Mutated Drone Specialization', 'Repair Drone Operation', 'Salvage Drone Operation', 'Salvage Drone Specialization', 'Sentry Drone Interfacing', 'Support Fighters'],
    'Electronic Systems': ['Burst Projector Operation', 'Burst Projector Operation', 'Cloaking', 'Cloaking', 'Electronic Warfare', 'Electronic Warfare', 'Frequency Modulation', 'Frequency Modulation', 'Long Distance Jamming', 'Long Distance Jamming', 'Propulsion Jamming', 'Propulsion Jamming', 'Sensor Linking', 'Sensor Linking', 'Signal Dispersion', 'Signal Dispersion', 'Signal Suppression', 'Signal Suppression', 'Signature Focusing', 'Signature Focusing', 'Signature Masking', 'Signature Masking', 'Tactical Logistics Reconfiguration', 'Tactical Logistics Reconfiguration', 'Target Painting', 'Target Painting', 'Weapon Destabilization', 'Weapon Destabilization', 'Weapon Disruption', 'Weapon Disruption'],
    'Engineering': ['Advanced Weapon Upgrades', 'CPU Management', 'Capacitor Emission Systems', 'Capacitor Management', 'Capacitor Systems Operation', 'Capital Capacitor Emission Systems', 'Electronics Upgrades', 'Energy Grid Upgrades', 'Energy Pulse Weapons', 'Nanite Interfacing', 'Nanite Operation', 'Power Grid Management', 'Resistance Phasing', 'Thermodynamics', 'Weapon Upgrades'],
    'Fleet Support': ['Armored Command', 'Armored Command Specialist', 'Command Burst Specialist', 'Expedition Command', 'Expedition Command Specialist', 'Fleet Command', 'Fleet Compression Logistics', 'Fleet Coordination', 'Fleet Formations', 'Information Command', 'Information Command Specialist', 'Leadership', 'Mining Director', 'Mining Foreman', 'Shield Command', 'Shield Command Specialist', 'Skirmish Command', 'Skirmish Command Specialist', 'Spatial Phenomena Generation', 'Wing Command'],
    'Gunnery': ['Advanced Doomsday Operation', 'Capital Artillery Specialization', 'Capital Autocannon Specialization', 'Capital Beam Laser Specialization', 'Capital Blaster Specialization', 'Capital Disintegrator Specialization', 'Capital Energy Turret', 'Capital Hybrid Turret', 'Capital Precursor Weapon', 'Capital Projectile Turret', 'Capital Pulse Laser Specialization', 'Capital Railgun Specialization', 'Controlled Bursts', 'Disruptive Lance Operation', 'Doomsday Operation', 'Doomsday Rapid Firing', 'Gunnery', 'Large Artillery Specialization', 'Large Autocannon Specialization', 'Large Beam Laser Specialization', 'Large Blaster Specialization', 'Large Disintegrator Specialization', 'Large Energy Turret', 'Large Hybrid Turret', 'Large Precursor Weapon', 'Large Projectile Turret', 'Large Pulse Laser Specialization', 'Large Railgun Specialization', 'Large Vorton Projector', 'Large Vorton Specialization', 'Medium Artillery Specialization', 'Medium Autocannon Specialization', 'Medium Beam Laser Specialization', 'Medium Blaster Specialization', 'Medium Disintegrator Specialization', 'Medium Energy Turret', 'Medium Hybrid Turret', 'Medium Precursor Weapon', 'Medium Projectile Turret', 'Medium Pulse Laser Specialization', 'Medium Railgun Specialization', 'Medium Vorton Projector', 'Medium Vorton Specialization', 'Motion Prediction', 'Rapid Firing', 'Sharpshooter', 'Small Artillery Specialization', 'Small Autocannon Specialization', 'Small Beam Laser Specialization', 'Small Blaster Specialization', 'Small Disintegrator Specialization', 'Small Energy Turret', 'Small Hybrid Turret', 'Small Precursor Weapon', 'Small Projectile Turret', 'Small Pulse Laser Specialization', 'Small Railgun Specialization', 'Small Vorton Projector', 'Small Vorton Specialization', 'Surgical Strike', 'Tactical Weapon Reconfiguration', 'Trajectory Analysis', 'Vorton Arc Extension', 'Vorton Arc Guidance', 'Vorton Power Amplification', 'Vorton Projector Operation'],
    'Missiles': ['Auto-Targeting Missiles', 'Bomb Deployment', 'Breacher Pod Clone Efficacity', 'Breacher Pod Clone Longevity', 'Breacher Pod Launcher Operation', 'Breacher Pod Projection', 'Breacher Pod Rapid Firing', 'Cruise Missile Specialization', 'Cruise Missiles', 'Defender Missiles', 'Guided Missile Precision', 'Heavy Assault Missile Specialization', 'Heavy Assault Missiles', 'Heavy Missile Specialization', 'Heavy Missiles', 'Light Missile Specialization', 'Light Missiles', 'Missile Bombardment', 'Missile Launcher Operation', 'Missile Projection', 'Rapid Launch', 'Rocket Specialization', 'Rockets', 'Target Navigation Prediction', 'Torpedo Specialization', 'Torpedoes', 'Warhead Upgrades', 'XL Cruise Missile Specialization', 'XL Cruise Missiles', 'XL Torpedo Specialization', 'XL Torpedoes'],
    'Navigation': ['Acceleration Control', 'Afterburner', 'Capital Jump Portal Generation', 'Capital Micro Jump Drive Operation', 'Cynosural Field Theory', 'Evasive Maneuvering', 'Fuel Conservation', 'High Speed Maneuvering', 'Jump Drive Calibration', 'Jump Drive Operation', 'Jump Fuel Conservation', 'Jump Portal Generation', 'Micro Jump Drive Operation', 'Navigation', 'Warp Drive Operation'],
    'Neural Enhancement': ['Advanced Infomorph Psychology', 'Biology', 'Cloning Facility Operation', 'Cybernetics', 'Elite Infomorph Psychology', 'Infomorph Psychology', 'Infomorph Synchronizing', 'Neurotoxin Control', 'Neurotoxin Recovery'],
    'Planet Management': ['Advanced Planetology', 'Advanced Planetology', 'Command Center Upgrades', 'Command Center Upgrades', 'Interplanetary Consolidation', 'Interplanetary Consolidation', 'Planetology', 'Planetology', 'Remote Sensing', 'Remote Sensing'],
    'Production': ['Advanced Capital Ship Construction', 'Advanced Industrial Ship Construction', 'Advanced Industry', 'Advanced Large Ship Construction', 'Advanced Mass Production', 'Advanced Medium Ship Construction', 'Advanced Small Ship Construction', 'Capital Ship Construction', 'Drug Manufacturing', 'Industry', 'Mass Production', 'Outpost Construction', 'Supply Chain Management'],
    'Resource Processing': ['Abyssal Ore Processing', 'Advanced Mass Reactions', 'Astrogeology', 'Capital Industrial Reconfiguration', 'Capital Shipboard Compression Technology', 'Coherent Ore Processing', 'Common Moon Ore Processing', 'Complex Ore Processing', 'Deep Core Mining', 'Erratic Ore Processing', 'Exceptional Moon Ore Processing', 'Gas Cloud Harvesting', 'Gas Decompression Efficiency', 'Ice Harvesting', 'Ice Processing', 'Industrial Reconfiguration', 'Mass Reactions', 'Mercoxit Ore Processing', 'Mining', 'Mining Exploitation', 'Mining Precision', 'Mining Upgrades', 'Rare Moon Ore Processing', 'Reactions', 'Remote Reactions', 'Reprocessing', 'Reprocessing Efficiency', 'Salvaging', 'Scrapmetal Processing', 'Shipboard Compression Technology', 'Simple Ore Processing', 'Ubiquitous Moon Ore Processing', 'Uncommon Moon Ore Processing', 'Unrefined Minerals Processing', 'Variegated Ore Processing'],
    'Rigging': ['Armor Rigging', 'Astronautics Rigging', 'Drones Rigging', 'Electronic Superiority Rigging', 'Energy Weapon Rigging', 'Hybrid Weapon Rigging', 'Jury Rigging', 'Launcher Rigging', 'Projectile Weapon Rigging', 'Shield Rigging'],
    'Scanning': ['Archaeology', 'Astrometric Acquisition', 'Astrometric Pinpointing', 'Astrometric Rangefinding', 'Astrometrics', 'Hacking', 'Survey'],
    'Science': ['Advanced Laboratory Operation', 'Amarr Encryption Methods', 'Amarr Starship Engineering', 'Astronautic Engineering', 'Caldari Encryption Methods', 'Caldari Starship Engineering', 'Core Subsystem Technology', 'Defensive Subsystem Technology', 'Electromagnetic Physics', 'Electronic Engineering', 'Gallente Encryption Methods', 'Gallente Starship Engineering', 'Graviton Physics', 'High Energy Physics', 'Hydromagnetic Physics', 'Laboratory Operation', 'Laser Physics', 'Mechanical Engineering', 'Metallurgy', 'Minmatar Encryption Methods', 'Minmatar Starship Engineering', 'Molecular Engineering', 'Mutagenic Stabilization', 'Nanite Engineering', 'Nuclear Physics', 'Offensive Subsystem Technology', 'Plasma Physics', 'Propulsion Subsystem Technology', 'Quantum Physics', 'Research', 'Research Project Management', 'Rocket Science', 'Science', 'Scientific Networking', 'Sleeper Encryption Methods', 'Sleeper Technology', 'Takmahl Technology', 'Talocan Technology', 'Triglavian Encryption Methods', 'Triglavian Quantum Engineering', 'Upwell Encryption Methods', 'Upwell Starship Engineering', 'Yan Jung Technology'],
    'Shields': ['Capital Shield Emission Systems', 'Capital Shield Operation', 'EM Shield Compensation', 'Explosive Shield Compensation', 'Invulnerability Core Operation', 'Kinetic Shield Compensation', 'Shield Compensation', 'Shield Emission Systems', 'Shield Management', 'Shield Operation', 'Shield Upgrades', 'Tactical Shield Manipulation', 'Thermal Shield Compensation'],
    'Social': ['Connections', 'Criminal Connections', 'Diplomacy', 'Distribution Connections', 'Fast Talk', 'Freelancing', 'Mining Connections', 'Negotiation', 'Security Connections', 'Social'],
    'Spaceship Command': ['Advanced Spaceship Command', 'Amarr Battlecruiser', 'Amarr Battleship', 'Amarr Carrier', 'Amarr Cruiser', 'Amarr Destroyer', 'Amarr Dreadnought', 'Amarr Freighter', 'Amarr Frigate', 'Amarr Hauler', 'Amarr Strategic Cruiser', 'Amarr Tactical Destroyer', 'Amarr Titan', 'Assault Frigates', 'Black Ops', 'Caldari Battlecruiser', 'Caldari Battleship', 'Caldari Carrier', 'Caldari Cruiser', 'Caldari Destroyer', 'Caldari Dreadnought', 'Caldari Freighter', 'Caldari Frigate', 'Caldari Hauler', 'Caldari Strategic Cruiser', 'Caldari Tactical Destroyer', 'Caldari Titan', 'Capital Industrial Ships', 'Capital Ships', 'Command Carriers', 'Command Destroyers', 'Command Ships', 'Covert Ops', 'EDENCOM Battleship', 'EDENCOM Battleship', 'EDENCOM Cruiser', 'EDENCOM Cruiser', 'EDENCOM Frigate', 'EDENCOM Frigate', 'Electronic Attack Ships', 'Exhumers', 'Expedition Command Ships', 'Expedition Frigates', 'Gallente Battlecruiser', 'Gallente Battleship', 'Gallente Carrier', 'Gallente Cruiser', 'Gallente Destroyer', 'Gallente Dreadnought', 'Gallente Freighter', 'Gallente Frigate', 'Gallente Hauler', 'Gallente Strategic Cruiser', 'Gallente Tactical Destroyer', 'Gallente Titan', 'Heavy Assault Cruisers', 'Heavy Interdiction Cruisers', 'Industrial Command Ships', 'Interceptors', 'Interdictors', 'Jump Freighters', 'Lancer Dreadnoughts', 'Logistics Cruisers', 'Logistics Frigates', 'Marauders', 'Mining Barge', 'Mining Destroyer', 'Mining Frigate', 'Minmatar Battlecruiser', 'Minmatar Battleship', 'Minmatar Carrier', 'Minmatar Cruiser', 'Minmatar Destroyer', 'Minmatar Dreadnought', 'Minmatar Freighter', 'Minmatar Frigate', 'Minmatar Hauler', 'Minmatar Strategic Cruiser', 'Minmatar Tactical Destroyer', 'Minmatar Titan', 'ORE Freighter', 'ORE Hauler', 'Precursor Battlecruiser', 'Precursor Battlecruiser', 'Precursor Battleship', 'Precursor Battleship', 'Precursor Cruiser', 'Precursor Cruiser', 'Precursor Destroyer', 'Precursor Destroyer', 'Precursor Dreadnought', 'Precursor Dreadnought', 'Precursor Frigate', 'Precursor Frigate', 'Recon Ships', 'Spaceship Command', 'Transport Ships', 'Upwell Freighter', 'Upwell Hauler'],
    'Structure Management': ['Anchoring'],
    'Subsystems': ['Amarr Core Systems', 'Amarr Defensive Systems', 'Amarr Offensive Systems', 'Amarr Propulsion Systems', 'Caldari Core Systems', 'Caldari Defensive Systems', 'Caldari Offensive Systems', 'Caldari Propulsion Systems', 'Gallente Core Systems', 'Gallente Defensive Systems', 'Gallente Offensive Systems', 'Gallente Propulsion Systems', 'Minmatar Core Systems', 'Minmatar Defensive Systems', 'Minmatar Offensive Systems', 'Minmatar Propulsion Systems'],
    'Targeting': ['Advanced Target Management', 'Gravimetric Sensor Compensation', 'Ladar Sensor Compensation', 'Long Range Targeting', 'Magnetometric Sensor Compensation', 'Radar Sensor Compensation', 'Signature Analysis', 'Target Management'],
    'Trade': ['Accounting', 'Advanced Broker Relations', 'Advanced Contracting', 'Broker Relations', 'Contracting', 'Corporation Contracting', 'Customs Code Expertise', 'Daytrading', 'Marketing', 'Procurement', 'Retail', 'Trade', 'Tycoon', 'Visibility', 'Wholesale'],
}
